LPS-189573 TOTP reuse | wip send email to user functionality
stian-sigvartsen/liferay-portal pull request #289
Opened 2023-10-10 18:06 UTC by manuelecastro

2023-10-10 18:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-11 16:08 UTC, stian-sigvartsen requested changes
Hi @manuelecastro. Generally this is a good implementation I think. I just left some comments for naming of things. Please can you review and re-send to `liferay-appsec`? Thanks!

2023-10-11 16:08 UTC, stian-sigvartsen commented on modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-timebased-otp-web/src/main/java/com/liferay/multi/factor/authentication/timebased/otp/web/internal/checker/TimeBasedOTPBrowserSetupMFAChecker.java
> +				mfaTimeBasedOTP, mfaTimeBasedOTPEntry.getLastValidTOTP())) {
This condition could be made into a simple "else" for the "if" block

2023-10-11 18:03 UTC, manuelecastro commented
PR sent to AppSec repo: https://github.com/liferay-appsec/liferay-portal/pull/1440

2023-10-11 18:03 UTC, closed without merging